### ISSUE TITLE
About Figure 14 in paper.

### ISSUE THREAD

**Issue by Alan-Qin** [tml-epfl/sam-low-rank-features#2]
Hi Maksym, 

I noticed that you mentioned that NN have larger gradient norm for other activation functions.
<img width="858" alt="image" src="https://github.com/tml-epfl/sam-low-rank-features/assets/43122728/510475bd-00ce-4c78-9598-e75fc096f579">

However, I found that there are some conficts:
<img width="868" alt="image" src="https://github.com/tml-epfl/sam-low-rank-features/assets/43122728/de0db57d-3a0a-4461-a986-41b14d76b750">

Are there some mistakes or do I misunderstand somethings?

Thanks for your time.
Zeyu

**Comment by max-andr** [comment]
Hi Zeyu,

Thanks for your interest in our work. 

So the paragraph above seems correct to me for all statements except _"higher weight norm"_. Indeed, you are right that for tanh and abs activations, the weight norm (note: we didn't plot the _gradient_ norm, only the _weight_ norm) is smaller, not higher, with SAM. In any case, the main observation is about the low-rank features, so I hope this typo won't distract too much from the main message :-)

Best,
Maksym
